#!/usr/bin/env python3

from os.path import join

import lib.config as config
from lib.net import download


def pop_dirs(repo):
    print('Downloading %s directory structure' % repo)
    repodata = config.repos[repo]

    urls = []

    for i in config.suites:
        for j in config.suites[i]:
            baseurl = join(repodata['host'], repodata['dists'])
            suite = j
            if repodata['aliases'] is True:
                if j in config.aliases[repodata['name']]:
                    suite = config.aliases[repodata['name']][j]
                elif repodata['skipmissing'] is True:
                    continue
                skips = ['jessie-security', 'ascii-security']  # XXX: hack
                if repo == 'debian' and j in skips:
                    continue
            pair = (join(baseurl, suite),
                    join(baseurl.replace(repodata['host'],
                         config.spooldir), suite))
            urls.append(pair)

    return urls

for dist in config.repos:
    dlurls = pop_dirs(dist)
    for url in dlurls:
        for file in config.mainrepofiles:
            remote = join(url[0], file)
            local = join(url[1], file)
            download(remote, local)
